# build the react app

FROM node:lts-alpine as stage-0
WORKDIR /app
COPY ./ /app/
RUN cd /app && npm ci

RUN cd /app && GENERATE_SOURCEMAP=false npm run build


RUN ls /app | echo
FROM nginx:alpine

COPY --from=stage-0 /app/build/ /usr/share/nginx/html
COPY --from=stage-0 /app/nginx/default.conf.template /etc/nginx/templates/
