# build the react app

FROM node:lts-alpine as stage-0
WORKDIR /app
COPY ./client /app/
RUN cd /app && npm ci

# CMD ["npm", "run", "build","&&","ls","/app"]
RUN cd /app && npm run build



RUN ls /app | echo
FROM nginx:alpine


COPY --from=stage-0 /app/build/ /usr/share/nginx/html
COPY --from=stage-0 /app/nginx.conf /etc/nginx/conf.d/default.conf

