version: "3.4"

services:
   db:
      image: postgres:15.1-alpine
      restart: always
      environment:
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=db
      ports:
         - 5432:5432
      volumes:
         - db:/var/lib/postgresql/data
   s3:
      image: minio/minio:latest
      command: server /data
      ports:
         - "9000:9000"
      volumes:
         - s3:/data
      environment:
         MINIO_ROOT_USER: minio_secret_key
         MINIO_ROOT_PASSWORD: minio_secret_key
         #  MINIO_ACCESS_KEY: minio_secret_key
         #  MINIO_SECRET_KEY: minio_secret_key
   static:
      image: partivity-static
      build:
         context: client
         dockerfile: ./Dockerfile.dev
      environment:
         NODE_ENV: development
         WATCHPACK_POLLING: true
      ports:
         - 3000:3000
      volumes:
         - ./client:/app
   api:
      image: partivity-api
      build:
         context: server
         dockerfile: ./Dockerfile.dev
      env_file: server/.env
      environment:
         NODE_ENV: development

         DB_PASSWORD: postgres
         DB_HOST: db
         DB_DATABASE: db
         DB_USERNAME: postgres
         DB_PORT: 5432
         DB_PROTOCOL: DEV

         MINIO_ACCESS_KEY: minio_secret_key
         MINIO_SECRET_KEY: minio_secret_key
         MINIO_HOST: s3
         MINIO_PORT: 9000
      ports:
         - 5000:5000
      volumes:
         - ./server:/app
volumes:
   s3:
   db:
