version: "3.4"

services:
   db:
      image: mysql:latest
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: pass
         MYSQL_DATABASE: db
         MYSQL_USER: user
         MYSQL_PASSWORD: pass
      ports:
         - 3306:3306
      volumes: # not working need to checkout why that is
         - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql
   static:
      image: partivity-static
      build:
         context: client
         dockerfile: ./Dockerfile.dev
      environment:
         NODE_ENV: development
      ports:
         - 3000:3000
      volumes:
         - ./client:/app
   api:
      image: partivity-api
      build:
         context: server
         dockerfile: ./Dockerfile.dev
      env_file: server/.env
      environment:
         NODE_ENV: development
         MYSQL_PASSWORD: pass
         MYSQL_HOST: db
         MYSQL_DATABASE: db
         MYSQL_USERNAME: user
         MYSQL_PORT: 3306
         MYSQL_PROTOCOL: DEV
      ports:
         - 5000:5000
      volumes:
         - ./server:/app
