version: "3.4"

services:
   db:
      image: mysql:latest
      command: --authentication_policy=mysql_native_password
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: pass
         MYSQL_DATABASE: db
         MYSQL_USER: user
         MYSQL_PASSWORD: pass
      ports:
         - 3306:3306
      volumes: # not working need to checkout why that is
         - ./init:/docker-entrypoint-initdb.d
         - mysql:/var/lib/mysql
   s3:
      image: minio/minio:latest
      command: server /data
      ports:
         - "9000:9000"
      volumes:
         - s3:/data
      environment:
         MINIO_ROOT_USER: minio_secret_key
         MINIO_ROOT_PASSWORD: minio_secret_key
         #  MINIO_ACCESS_KEY: minio_secret_key
         #  MINIO_SECRET_KEY: minio_secret_key
   static:
      image: partivity-static
      build:
         context: client
         dockerfile: ./Dockerfile.dev
      environment:
         NODE_ENV: development
         WATCHPACK_POLLING: true
      ports:
         - 3000:3000
      volumes:
         - ./client:/app
   api:
      image: partivity-api
      build:
         context: server
         dockerfile: ./Dockerfile.dev
      env_file: server/.env
      environment:
         NODE_ENV: development
         MYSQL_PASSWORD: pass
         MYSQL_HOST: db
         MYSQL_DATABASE: db
         MYSQL_USERNAME: user
         MYSQL_PORT: 3306
         MYSQL_PROTOCOL: DEV
         MINIO_ACCESS_KEY: minio_secret_key
         MINIO_SECRET_KEY: minio_secret_key
         MINIO_HOST: s3
         MINIO_PORT: 9000
      ports:
         - 5000:5000
      volumes:
         - ./server:/app
volumes:
   s3:
   mysql:
