FROM node:lts-alpine
WORKDIR /app
# COPY ["./server/package*.json", "/app"]
# COPY ["./server/package-lock.json", "/app"]
COPY ./server /app

RUN cd /app &&  npm ci
ENV NODE_ENV=production
EXPOSE 5000

RUN npm run build
CMD ["npm", "run" ,"start:prod"]
