FROM node:lts-alpine
WORKDIR /app
COPY ["package*.json", "/app"]
COPY ["package-lock.json", "/app"]
COPY . /app

RUN cd /app &&  npm ci
ENV NODE_ENV=production
EXPOSE 5000
CMD ["npm", "run" ,"start:prod"]
